version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ouija-postgres
    environment:
      POSTGRES_USER: ouija_user
      POSTGRES_PASSWORD: ouija_pass
      POSTGRES_DB: ouija_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ouija_user -d ouija_db']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ouija-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # Ollama (opcional - comentar si se usa instalación local)
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ouija-ollama
  #   ports:
  #     - '11434:11434'
  #   volumes:
  #     - ollama-data:/root/.ollama

volumes:
  postgres-data:
  redis-data:
  # ollama-data:
